name: linting, testing, building
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install modules
        run: npm install --force
      - name: building production project
        run: npm run build:prod
        if: always()
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting scss
        run: npm run lint:scss
        if: always()
      - name: run unit tests
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci